import Fastify from 'fastify';
import cors from '@fastify/cors';
import { Server } from 'socket.io';
import { createHmac, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { db, initDb, closeDb } from './db.js';
const app=Fastify({logger:true,bodyLimit:256*1024});
const configuredOrigins=process.env.WEB_ORIGIN?.split(',').map(v=>v.trim()).filter(Boolean)??[];
const corsOrigin=configuredOrigins.length?configuredOrigins:true;
await app.register(cors,{origin:corsOrigin});
const secret=process.env.SESSION_SECRET?.trim();
if(!secret)throw new Error('SESSION_SECRET is required in production');
const SESSION_SECRET=secret;
type PublicUser={id:string;name:string;email?:string;phoneNumber?:string;username?:string;createdAt:string;online:boolean;token?:string};
type Message={id:string;chatId:string;senderId:string;text:string;createdAt:string;delivered:boolean;read:boolean};
const normalize=(v:unknown)=>String(v??'').trim().toLowerCase();
const normalizePhone=(v:unknown)=>String(v??'').replace(/[\s().-]/g,'').trim();
const hashPassword=(password:string)=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`};
function verifyPassword(password:string,stored?:string){try{if(!stored)return false;const [salt,encoded]=stored.split(':');if(!salt||!encoded)return false;const expected=Buffer.from(encoded,'hex'),actual=scryptSync(password,salt,64);return actual.length===expected.length&&timingSafeEqual(actual,expected)}catch{return false}}
const sign=(payload:string)=>createHmac('sha256',SESSION_SECRET).update(payload).digest('hex');
const createToken=(userId:string)=>{const payload=Buffer.from(JSON.stringify({userId,issuedAt:Date.now()})).toString('base64url');return `${payload}.${sign(payload)}`};
function verifyToken(token:string){try{const [payload,signature]=token.split('.');if(!payload||!signature)return null;const expected=sign(payload);if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')) as {userId?:string;issuedAt?:number};if(!data.userId||!data.issuedAt||Date.now()-data.issuedAt>30*24*60*60*1000)return null;return data.userId}catch{return null}}
const getBearerUser=(request:any)=>{const h=String(request.headers.authorization||'');return h.startsWith('Bearer ')?verifyToken(h.slice(7)):null};
function toPublicUser(user:any,token?:string):PublicUser{return{id:String(user.id),name:String(user.name),email:user.email??undefined,phoneNumber:user.phone_number??undefined,username:user.username??undefined,createdAt:new Date(user.created_at).toISOString(),online:Boolean(user.online),...(token?{token}:{})}}
const chatParticipants=(chatId:string)=>chatId.split(':');
const connectedUsers=new Map<string,string>();
await initDb();
const codeHash=(code:string)=>createHmac('sha256',SESSION_SECRET).update(`auth-code:${code}`).digest('hex');
const makeCode=()=>String(Math.floor(100000+Math.random()*900000));
async function sendEmail(to:string,subject:string,html:string){const key=process.env.RESEND_API_KEY?.trim();if(!key)return false;const from=process.env.RESEND_FROM?.trim()||'Pro Chat <onboarding@resend.dev>';const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})});if(!response.ok){app.log.error({status:response.status},'email provider rejected message');return false}return true}
async function issueCode(userId:string,purpose:'verify_email'|'password_reset'){const recent=await db.query('SELECT COUNT(*)::int AS count FROM pro_chat_auth_codes WHERE user_id=$1 AND purpose=$2 AND created_at>NOW()-INTERVAL \'15 minutes\'',[userId,purpose]);if(Number(recent.rows[0]?.count||0)>=3)return {limited:true};await db.query('DELETE FROM pro_chat_auth_codes WHERE user_id=$1 AND purpose=$2',[userId,purpose]);const code=makeCode();await db.query('INSERT INTO pro_chat_auth_codes(id,user_id,code_hash,purpose,expires_at) VALUES($1,$2,$3,$4,NOW()+INTERVAL \'10 minutes\')',[randomUUID(),userId,codeHash(code),purpose]);return {code,limited:false}}
async function consumeCode(userId:string,purpose:string,code:string){const result=await db.query('SELECT * FROM pro_chat_auth_codes WHERE user_id=$1 AND purpose=$2 AND expires_at>NOW() ORDER BY created_at DESC LIMIT 1',[userId,purpose]);const row=result.rows[0];if(!row)return {ok:false,error:'Code is invalid or expired'};if(Number(row.attempts)>=5){await db.query('DELETE FROM pro_chat_auth_codes WHERE id=$1',[row.id]);return {ok:false,error:'Too many attempts. Request a new code.'}};await db.query('UPDATE pro_chat_auth_codes SET attempts=attempts+1 WHERE id=$1',[row.id]);if(row.code_hash!==codeHash(code))return {ok:false,error:'Invalid verification code'};await db.query('DELETE FROM pro_chat_auth_codes WHERE id=$1',[row.id]);return {ok:true}}
app.get('/health',async()=>({ok:true,service:'pro-chat',database:'neon-postgresql',time:new Date().toISOString()}));
app.post<{Body:{email?:string;phoneNumber?:string;username?:string;password?:string}}>('/api/auth/register',async(request,reply)=>{const email=normalize(request.body?.email),phoneNumber=normalizePhone(request.body?.phoneNumber),username=normalize(request.body?.username),password=String(request.body?.password||'');if(!email.includes('@'))return reply.code(400).send({error:'Enter a valid email address'});if(phoneNumber.replace(/\D/g,'').length<7)return reply.code(400).send({error:'Enter a valid phone number'});if(!/^[a-z0-9_]{3,30}$/.test(username))return reply.code(400).send({error:'Username must be 3-30 characters using letters, numbers, or underscore'});if(password.length<8)return reply.code(400).send({error:'Password must contain at least 8 characters'});const duplicate=await db.query('SELECT id FROM pro_chat_users WHERE email=$1 OR phone_number=$2 OR username=$3 LIMIT 1',[email,phoneNumber,username]);if(duplicate.rowCount)return reply.code(409).send({error:'An account already exists with that email, phone number, or username'});const id=randomUUID(),createdAt=new Date();await db.query('INSERT INTO pro_chat_users(id,name,created_at,email,phone_number,username,password_hash,email_verified) VALUES($1,$2,$3,$4,$5,$6,$7,false)',[id,username,createdAt,email,phoneNumber,username,hashPassword(password)]);const issued=await issueCode(id,'verify_email');if(issued.limited)return reply.code(429).send({error:'Too many verification requests. Please try again later'});const sent=await sendEmail(email,'Verify your Pro Chat email',`<h2>Verify your Pro Chat account</h2><p>Your verification code is:</p><p style="font-size:28px;font-weight:700;letter-spacing:6px">${issued.code}</p><p>This code expires in 10 minutes.</p>`);if(!sent){await db.query('DELETE FROM pro_chat_users WHERE id=$1',[id]);return reply.code(503).send({error:'Email service is not configured. Please configure RESEND_API_KEY and RESEND_FROM on the Pro Chat server.'})}return{requiresVerification:true,email,username,message:'Verification code sent to your email'} });
app.post<{Body:{email?:string;code?:string}}>('/api/auth/verify-email',async(request,reply)=>{const email=normalize(request.body?.email),code=String(request.body?.code||'').trim();if(!email||!/^[0-9]{6}$/.test(code))return reply.code(400).send({error:'Enter the 6-digit verification code'});const result=await db.query('SELECT * FROM pro_chat_users WHERE email=$1 LIMIT 1',[email]);const user=result.rows[0];if(!user)return reply.code(400).send({error:'Invalid verification code'});const check=await consumeCode(user.id,'verify_email',code);if(!check.ok)return reply.code(400).send({error:check.error});await db.query('UPDATE pro_chat_users SET email_verified=true WHERE id=$1',[user.id]);const token=createToken(user.id);await db.query('INSERT INTO pro_chat_sessions(token,user_id,created_at,expires_at) VALUES($1,$2,NOW(),NOW()+INTERVAL \'30 days\')',[token,user.id]);return{...toPublicUser({...user,email_verified:true},token),emailVerified:true}});
app.post<{Body:{email?:string}}>('/api/auth/resend-verification',async(request,reply)=>{const email=normalize(request.body?.email);const result=await db.query('SELECT * FROM pro_chat_users WHERE email=$1 LIMIT 1',[email]);const user=result.rows[0];if(user&&!user.email_verified){const issued=await issueCode(user.id,'verify_email');if(issued.limited)return reply.code(429).send({error:'Too many verification requests. Please try again later'});await sendEmail(email,'Your Pro Chat verification code',`<h2>Verify your Pro Chat account</h2><p>Your new verification code is:</p><p style="font-size:28px;font-weight:700;letter-spacing:6px">${issued.code}</p><p>This code expires in 10 minutes.</p>`)}return{message:'If the account requires verification, a new code has been sent.'}});
app.post<{Body:{identifier?:string;password?:string}}>('/api/auth/login',async(request,reply)=>{const identifier=String(request.body?.identifier||'').trim(),password=String(request.body?.password||'');if(!identifier||!password)return reply.code(400).send({error:'Enter your login details'});const result=await db.query('SELECT * FROM pro_chat_users WHERE email=$1 OR phone_number=$2 OR username=$3 LIMIT 1',[normalize(identifier),normalizePhone(identifier),normalize(identifier)]);const user=result.rows[0];if(!user||!verifyPassword(password,user.password_hash))return reply.code(401).send({error:'Invalid username, email/phone, or password'});if(user.email&&!user.email_verified)return reply.code(403).send({error:'EMAIL_NOT_VERIFIED',email:user.email});const token=createToken(user.id);await db.query('INSERT INTO pro_chat_sessions(token,user_id,created_at,expires_at) VALUES($1,$2,NOW(),NOW()+INTERVAL \'30 days\')',[token,user.id]);return toPublicUser(user,token)});
app.post<{Body:{identifier?:string}}>('/api/auth/forgot-password',async(request)=>{const identifier=String(request.body?.identifier||'').trim();const result=await db.query('SELECT * FROM pro_chat_users WHERE email=$1 OR phone_number=$2 OR username=$3 LIMIT 1',[normalize(identifier),normalizePhone(identifier),normalize(identifier)]);const user=result.rows[0];if(user?.email){const issued=await issueCode(user.id,'password_reset');if(!issued.limited)await sendEmail(user.email,'Pro Chat password reset code',`<h2>Reset your Pro Chat password</h2><p>Your password reset code is:</p><p style="font-size:28px;font-weight:700;letter-spacing:6px">${issued.code}</p><p>This code expires in 10 minutes. If you did not request this, ignore this email.</p>`)}return{message:'If the account exists and has an email address, a reset code has been sent.'}});
app.post<{Body:{identifier?:string;code?:string;password?:string}}>('/api/auth/reset-password',async(request,reply)=>{const identifier=String(request.body?.identifier||'').trim(),code=String(request.body?.code||'').trim(),password=String(request.body?.password||'');if(password.length<8)return reply.code(400).send({error:'Password must contain at least 8 characters'});const result=await db.query('SELECT * FROM pro_chat_users WHERE email=$1 OR phone_number=$2 OR username=$3 LIMIT 1',[normalize(identifier),normalizePhone(identifier),normalize(identifier)]);const user=result.rows[0];if(!user)return reply.code(400).send({error:'Invalid reset code'});const check=await consumeCode(user.id,'password_reset',code);if(!check.ok)return reply.code(400).send({error:check.error});await db.query('UPDATE pro_chat_users SET password_hash=$1 WHERE id=$2',[hashPassword(password),user.id]);await db.query('DELETE FROM pro_chat_sessions WHERE user_id=$1',[user.id]);return{ok:true,message:'Password reset successfully'}});
app.post('/api/session',async(request:any,reply)=>{const userId=getBearerUser(request);if(!userId)return reply.code(401).send({error:'Authentication required'});const result=await db.query('SELECT * FROM pro_chat_users WHERE id=$1',[userId]);if(!result.rowCount)return reply.code(401).send({error:'User not found'});const token=createToken(userId);await db.query('INSERT INTO pro_chat_sessions(token,user_id,created_at,expires_at) VALUES($1,$2,NOW(),NOW()+INTERVAL \'30 days\')',[token,userId]);return toPublicUser(result.rows[0],token)});
app.get('/api/users',async(request:any,reply)=>{const userId=getBearerUser(request),query=normalize(request.query?.q||'');if(query.length>100)return reply.code(400).send({error:'Search text is too long'});const phoneQuery=normalizePhone(query);const result=await db.query(`SELECT id,name,email,phone_number,username,created_at,online FROM pro_chat_users WHERE id<>$1 AND ($2='' OR LOWER(username) LIKE $3 OR LOWER(name) LIKE $3 OR LOWER(email) LIKE $3 OR phone_number LIKE $4) ORDER BY CASE WHEN LOWER(username)=$2 THEN 0 WHEN LOWER(username) LIKE $5 THEN 1 ELSE 2 END,name LIMIT 50`,[userId||'',query,`%${query}%`,`%${phoneQuery}%`,`${query}%`]);return result.rows.map(user=>toPublicUser(user))});
app.get<{Params:{chatId:string}}>('/api/messages/:chatId',async(request,reply)=>{const userId=getBearerUser(request);if(!userId)return reply.code(401).send({error:'Authentication required'});const participants=chatParticipants(request.params.chatId);if(participants.length!==2||!participants.includes(userId))return reply.code(403).send({error:'Conversation access denied'});const result=await db.query(`SELECT id,chat_id AS "chatId",sender_id AS "senderId",text,created_at AS "createdAt",delivered,read FROM pro_chat_messages WHERE chat_id=$1 ORDER BY created_at ASC LIMIT 200`,[request.params.chatId]);return result.rows});
const io=new Server(app.server,{cors:{origin: corsOrigin,methods:['GET','POST']},maxHttpBufferSize:256*1024});
io.use((socket,next)=>{const userId=verifyToken(String(socket.handshake.auth?.token||''));if(!userId)return next(new Error('Authentication required'));socket.data.userId=userId;next()});
io.on('connection',socket=>{const userId=String(socket.data.userId);connectedUsers.set(socket.id,userId);void db.query('UPDATE pro_chat_users SET online=true WHERE id=$1',[userId]);io.emit('presence:update',{userId,online:true});socket.on('chat:join',(chatId:string)=>{const p=chatParticipants(String(chatId));if(p.length===2&&p.includes(userId))socket.join(`chat:${chatId}`)});socket.on('message:send',async(input:any,acknowledge?:Function)=>{try{const chatId=String(input?.chatId||''),text=String(input?.text||'').trim(),p=chatParticipants(chatId);if(!chatId||!text||p.length!==2||!p.includes(userId)){acknowledge?.({ok:false,error:'Invalid message'});return}const message:Message={id:String(input?.id||randomUUID()),chatId,senderId:userId,text:text.slice(0,10000),createdAt:String(input?.createdAt||new Date().toISOString()),delivered:false,read:false};const existing=await db.query('SELECT id,chat_id AS "chatId",sender_id AS "senderId",text,created_at AS "createdAt",delivered,read FROM pro_chat_messages WHERE id=$1',[message.id]);if(existing.rowCount){acknowledge?.({ok:true,message:existing.rows[0]});return}const recipient=p.find(id=>id!==userId) as string;message.delivered=Array.from(connectedUsers.values()).includes(recipient);await db.query('INSERT INTO pro_chat_messages(id,chat_id,sender_id,text,created_at,delivered,read) VALUES($1,$2,$3,$4,$5,$6,$7)',[message.id,message.chatId,message.senderId,message.text,message.createdAt,message.delivered,false]);for(const [socketId,connectedUserId] of connectedUsers.entries())if(p.includes(connectedUserId))io.to(socketId).emit('message:new',message);acknowledge?.({ok:true,message})}catch(error){app.log.error(error);acknowledge?.({ok:false,error:'Message could not be saved'})}});socket.on('message:read',async(payload:any)=>{const chatId=String(payload?.chatId||''),messageId=String(payload?.messageId||'');if(!chatId||!chatParticipants(chatId).includes(userId))return;if(messageId)await db.query('UPDATE pro_chat_messages SET read=true WHERE id=$1 AND chat_id=$2 AND sender_id<>$3',[messageId,chatId,userId]);else await db.query('UPDATE pro_chat_messages SET read=true WHERE chat_id=$1 AND sender_id<>$2',[chatId,userId])});socket.on('disconnect',async()=>{connectedUsers.delete(socket.id);if(!Array.from(connectedUsers.values()).includes(userId)){await db.query('UPDATE pro_chat_users SET online=false WHERE id=$1',[userId]);io.emit('presence:update',{userId,online:false})}})});
setInterval(()=>{void db.query('DELETE FROM pro_chat_sessions WHERE expires_at<NOW()').catch(e=>app.log.error(e));void db.query('DELETE FROM pro_chat_reset_tokens WHERE expires_at<NOW()').catch(e=>app.log.error(e));void db.query('DELETE FROM pro_chat_auth_codes WHERE expires_at<NOW()').catch(e=>app.log.error(e))},6*60*60*1000).unref();
const port=Number(process.env.PORT||3000);await app.listen({port,host:'0.0.0.0'});app.log.info(`Pro Chat server listening on ${port}`);const shutdown=async()=>{await closeDb();process.exit(0)};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
