import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MessageCircle,Search,Send,Phone,Video,MoreVertical,Check,CheckCheck,LogOut,Star,Archive,Settings,Shield,User,ChevronDown,ChevronLeft,X,Smile,Paperclip,PhoneOff,Mic,MicOff,Camera,CameraOff,SwitchCamera,Bell} from 'lucide-react';
import './styles.css';

const isLocalHost=['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname);
const isGitHubPages=/\.github\.io$/i.test(location.hostname);
const isViteDev=location.port==='5173'||location.port==='4173';
const CONFIG_API=import.meta.env.VITE_API_URL||window.__PRO_CHAT_API__||'';
const LOCAL_MODE=isGitHubPages&&!CONFIG_API;
const localApiHost=location.hostname==='0.0.0.0'?'localhost':location.hostname;
const API=CONFIG_API||(isLocalHost||isViteDev?`http://${localApiHost}:3000`:location.origin);
const REALTIME_API=import.meta.env.VITE_REALTIME_URL||window.__PRO_CHAT_REALTIME__||(isLocalHost||isViteDev?`http://${localApiHost}:3001`:location.origin);
const USER_KEY='pro-chat-user-v3',CHATS_KEY='pro-chat-chats-v3',MSG_KEY='pro-chat-messages-v3',OUTBOX_KEY='pro-chat-outbox-v1',UNREAD_KEY='pro-chat-unread-v1';
const cid=(a,b)=>[a,b].sort().join(':');
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
if('serviceWorker' in navigator&&!import.meta.env.DEV)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
const EMOJIS=['😀','😂','🤣','😊','😍','🥰','😘','😎','🤔','😭','😡','👍','👎','👏','🙏','❤️','🔥','🎉','💯','✨','😄','😉','🤗','😇','🤩','😢','😮','🥳','❤️‍🔥','💙','💚','💛','🧡','💜','🤝','🙌','💪','👀','🎂','🎁','🚀','🌍','☀️','🌙'];
function tone(freq=520,duration=.08,volume=.025){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch{}}
function requestNotifications(){if('Notification' in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}
function notify(title,body){tone(700,.09,.02);if('Notification' in window&&Notification.permission==='granted'&&document.visibilityState!=='visible')new Notification(title,{body,icon:'./icons/icon-192.png'});}

function App(){
 const me=read(USER_KEY,null);
 const[chats,setChats]=useState(()=>read(CHATS_KEY,[]).map(c=>({...c,favorite:!!c.favorite,archived:!!c.archived})));
 const[messages,setMessages]=useState(()=>read(MSG_KEY,{}));
 const[unread,setUnread]=useState(()=>read(UNREAD_KEY,{}));
 const[stats,setStats]=useState({messagesSent:0,unreadMessages:0});
 const[search,setSearch]=useState('');const[results,setResults]=useState([]);const[searching,setSearching]=useState(false);const[searchError,setSearchError]=useState('');
 const[active,setActive]=useState(null);const[text,setText]=useState('');const[folder,setFolder]=useState('all');const[profileOpen,setProfileOpen]=useState(false);const[chatMenu,setChatMenu]=useState(false);const[profileView,setProfileView]=useState(null);const[emojiOpen,setEmojiOpen]=useState(false);const[typing,setTyping]=useState(false);const[attachment,setAttachment]=useState(null);const[toast,setToast]=useState('');
 const[call,setCall]=useState(null);const[filter,setFilter]=useState('natural');const[muted,setMuted]=useState(false);const[cameraOff,setCameraOff]=useState(false);
 const socketRef=useRef(null),signalRef=useRef(null),typingTimer=useRef(null),fileRef=useRef(null),pcRef=useRef(null),localStreamRef=useRef(null),pendingOfferRef=useRef(null),pendingIceRef=useRef([]),ringTimer=useRef(null),remoteVideoRef=useRef(null),localVideoRef=useRef(null);
 useEffect(()=>localStorage.setItem(CHATS_KEY,JSON.stringify(chats)),[chats]);
 useEffect(()=>localStorage.setItem(MSG_KEY,JSON.stringify(messages)),[messages]);
 useEffect(()=>localStorage.setItem(UNREAD_KEY,JSON.stringify(unread)),[unread]);
 useEffect(()=>{if(!me?.token||LOCAL_MODE)return;let disposed=false;import('socket.io-client').then(({io})=>{if(disposed)return;const s=io(API,{auth:{token:me.token},transports:['websocket','polling'],reconnection:true});socketRef.current=s;s.on('connect',()=>{read(OUTBOX_KEY,[]).forEach(m=>s.emit('message:send',m));localStorage.setItem(OUTBOX_KEY,'[]');requestNotifications()});s.on('message:new',receive);s.on('message:ack',p=>p?.message&&receive(p.message));}).catch(()=>{});return()=>{disposed=true;clearTimeout(typingTimer.current);socketRef.current?.disconnect();socketRef.current=null}},[me?.token]);
 useEffect(()=>{if(!me?.token||LOCAL_MODE)return;let disposed=false;import('socket.io-client').then(({io})=>{if(disposed)return;const s=io(REALTIME_API,{auth:{token:me.token},transports:['websocket','polling'],reconnection:true});signalRef.current=s;
   s.on('typing:update',p=>{if(p?.chatId===active&&p.userId!==me.id){setTyping(Boolean(p.typing));if(p.typing)tone(520,.055,.012)}});
   s.on('call:incoming',p=>{if(!p?.callId)return;if(call){s.emit('call:reject',{chatId:p.chatId,callId:p.callId,reason:'busy'});return}setCall({phase:'incoming',callId:p.callId,chatId:p.chatId,video:!!p.video,callerId:p.callerId,username:p.username||'contact'});startRing()});
   s.on('call:started',async p=>{if(!p?.callId)return;setCall(c=>c?{...c,phase:'calling',callId:p.callId}:c);await makeOffer(p.callId,p.chatId,!!p.video)});
   s.on('call:offer',async p=>{if(!p?.callId)return;if(!pcRef.current){pendingOfferRef.current=p;return}await pcRef.current.setRemoteDescription(new RTCSessionDescription(p.offer));await flushIce();const answer=await pcRef.current.createAnswer();await pcRef.current.setLocalDescription(answer);signalRef.current?.emit('call:answer',{chatId:p.chatId,callId:p.callId,answer});setCall(c=>c?{...c,phase:'connecting'}:c)});
   s.on('call:answer',async p=>{if(pcRef.current&&p?.answer){await pcRef.current.setRemoteDescription(new RTCSessionDescription(p.answer));await flushIce();setCall(c=>c?{...c,phase:'connected'}:c)}});
   s.on('call:ice',async p=>{if(!p?.candidate)return;if(pcRef.current&&pcRef.current.remoteDescription)await pcRef.current.addIceCandidate(new RTCIceCandidate(p.candidate));else pendingIceRef.current.push(p.candidate)});
   s.on('call:unavailable',()=>{stopCall(false);setToast('User is offline. Calling will notify them when they are online.')});
   s.on('call:reject',()=>{stopCall(false);setToast('Call declined')});
   s.on('call:end',()=>{stopCall(false);setToast('Call ended')});
 }).catch(()=>{});return()=>{disposed=true;signalRef.current?.disconnect();signalRef.current=null}},[me?.token,active,call]);
 useEffect(()=>{if(remoteVideoRef.current&&call?.remoteStream)remoteVideoRef.current.srcObject=call.remoteStream;if(localVideoRef.current&&call?.localStream)localVideoRef.current.srcObject=call.localStream},[call?.remoteStream,call?.localStream]);
 useEffect(()=>{if(!me?.token||LOCAL_MODE)return;fetch(`${REALTIME_API}/api/stats`,{headers:{Authorization:`Bearer ${me.token}`},cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>d&&setStats(d)).catch(()=>{})},[me?.token,unread]);
 function receive(m){if(!m?.chatId||!m?.id)return;setMessages(p=>({...p,[m.chatId]:[...(p[m.chatId]||[]).filter(x=>x.id!==m.id),m].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))}));setChats(p=>p.map(c=>c.id===m.chatId?{...c,lastMessage:m.text||'Attachment',lastAt:m.createdAt}:c));if(m.senderId!==me.id&&m.chatId!==active){setUnread(p=>({...p,[m.chatId]:(p[m.chatId]||0)+1}));notify(`New message from @${m.senderUsername||'contact'}`,m.text||'Attachment')}}
 async function find(q=search){const v=q.trim();setSearchError('');if(!v){setResults([]);return}setSearching(true);try{const r=await fetch(`${API}/api/users?q=${encodeURIComponent(v)}`,{headers:{Authorization:`Bearer ${me.token}`},cache:'no-store'});const d=await r.json().catch(()=>[]);if(!r.ok)throw Error(d.error||`Search failed (${r.status})`);const users=Array.isArray(d)?d.filter(u=>u.id!==me.id):[];setResults(users);if(!users.length)setSearchError('No user found. Try the exact username, email or phone number.')}catch(e){setResults([]);setSearchError(e.message==='Failed to fetch'||e.name==='TypeError'?'Cannot reach the Pro Chat server.':e.message||'Unable to search users.')}finally{setSearching(false)}}
 function activateChat(id){setActive(id);setUnread(p=>{const n={...p};delete n[id];return n});setSearch('');setResults([]);setSearchError('');setChatMenu(false);setEmojiOpen(false);setAttachment(null);setTyping(false)}
 async function openUser(u){if(!u?.id||u.id===me.id)return;const id=cid(me.id,u.id);activateChat(id);setChats(p=>p.some(c=>c.id===id)?p:p.concat([{id,userId:u.id,name:u.name||u.username||'Contact',username:u.username||'',email:u.email||'',phoneNumber:u.phoneNumber||'',lastMessage:'',lastAt:u.createdAt||new Date().toISOString(),favorite:false,archived:false}]));if(LOCAL_MODE)return;socketRef.current?.emit('chat:join',id);signalRef.current?.emit('chat:join',id);try{const r=await fetch(`${API}/api/messages/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${me.token}`},cache:'no-store'});if(r.ok){const d=await r.json();setMessages(p=>({...p,[id]:Array.isArray(d)?d:[]}))}}catch{}}
 function openChat(c){if(!c?.id)return;activateChat(c.id);socketRef.current?.emit('chat:join',c.id);signalRef.current?.emit('chat:join',c.id)}
 function toggleFavorite(id){setChats(p=>p.map(c=>c.id===id?{...c,favorite:!c.favorite}:c))}
 function toggleArchive(id){setChats(p=>p.map(c=>c.id===id?{...c,archived:!c.archived}:c));setChatMenu(false);if(folder==='archived'&&active===id)setActive(null)}
 function emitTyping(value){if(!signalRef.current?.connected||!active)return;signalRef.current.emit(value?'typing:start':'typing:stop',{chatId:active});clearTimeout(typingTimer.current);if(value)typingTimer.current=setTimeout(()=>signalRef.current?.emit('typing:stop',{chatId:active}),1500)}
 function send(){const v=text.trim(),c=chats.find(x=>x.id===active);if(!c||(!v&&!attachment))return;const m={id:crypto.randomUUID(),chatId:active,senderId:me.id,senderName:me.name,senderUsername:me.username,receiverId:c.userId,text:v||`📎 ${attachment?.name||'Attachment'}`,createdAt:new Date().toISOString(),status:'sent',attachment:attachment?{name:attachment.name,type:attachment.type,size:attachment.size,url:attachment.url}:undefined};receive(m);setText('');setAttachment(null);setEmojiOpen(false);emitTyping(false);tone(660,.05,.015);if(LOCAL_MODE)return;if(socketRef.current?.connected)socketRef.current.emit('message:send',m);else{const q=read(OUTBOX_KEY,[]);q.push(m);localStorage.setItem(OUTBOX_KEY,JSON.stringify(q))}}
 function chooseFile(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>25*1024*1024){setToast('Attachment is too large. Maximum 25 MB.');return}setAttachment({name:f.name,type:f.type||'application/octet-stream',size:f.size,url:URL.createObjectURL(f)})}
 function insertEmoji(e){setText(v=>v+e);setEmojiOpen(false)}
 function startRing(){stopRing();tone(900,.18,.04);ringTimer.current=setInterval(()=>{tone(900,.18,.04);setTimeout(()=>tone(700,.18,.035),230)},1000)}
 function stopRing(){if(ringTimer.current){clearInterval(ringTimer.current);ringTimer.current=null}}
 async function media(video){if(!navigator.mediaDevices?.getUserMedia){throw Error('Camera and microphone require HTTPS or localhost.')};return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1},video:video?{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30},facingMode:'user'}:false})}
 function newPeer(callId,chatId,video){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});pc.onicecandidate=e=>e.candidate&&signalRef.current?.emit('call:ice',{chatId,callId,candidate:e.candidate});pc.ontrack=e=>setCall(c=>c?{...c,remoteStream:e.streams[0]}:c);pc.onconnectionstatechange=()=>{if(['connected','completed'].includes(pc.connectionState))setCall(c=>c?{...c,phase:'connected'}:c);if(['failed','closed','disconnected'].includes(pc.connectionState)&&call)stopCall(false)};pcRef.current=pc;return pc}
 async function makeOffer(callId,chatId,video){try{const pc=pcRef.current||newPeer(callId,chatId,video);const stream=localStreamRef.current||await media(video);localStreamRef.current=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));setCall(c=>c?{...c,localStream:stream}:c);const offer=await pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:video});await pc.setLocalDescription(offer);signalRef.current?.emit('call:offer',{chatId,callId,offer});}catch(e){setToast(e.message||'Unable to start call');stopCall(false)}}
 async function flushIce(){const pc=pcRef.current;for(const c of pendingIceRef.current){try{await pc?.addIceCandidate(new RTCIceCandidate(c))}catch{}}pendingIceRef.current=[]}
 async function startCall(video){if(!active||call)return;requestNotifications();const c=chats.find(x=>x.id===active);try{const stream=await media(video);localStreamRef.current=stream;const callId=crypto.randomUUID();newPeer(callId,active,video);stream.getTracks().forEach(t=>pcRef.current.addTrack(t,stream));setCall({phase:'starting',callId,chatId:active,video,username:c?.username||c?.name||'contact',localStream:stream});signalRef.current?.emit('call:start',{chatId:active,callId,video,username:me.username||me.name})}catch(e){setToast(e.message||'Camera/microphone permission is required')}}
 async function acceptCall(){if(!call)return;stopRing();try{const stream=await media(call.video);localStreamRef.current=stream;const pc=newPeer(call.callId,call.chatId,call.video);stream.getTracks().forEach(t=>pc.addTrack(t,stream));setCall(c=>({...c,phase:'connecting',localStream:stream}));const offer=pendingOfferRef.current;if(offer){pendingOfferRef.current=null;await pc.setRemoteDescription(new RTCSessionDescription(offer.offer));await flushIce();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);signalRef.current?.emit('call:answer',{chatId:call.chatId,callId:call.callId,answer})}}catch(e){setToast(e.message||'Unable to answer call');rejectCall()}}
 function rejectCall(){if(call)signalRef.current?.emit('call:reject',{chatId:call.chatId,callId:call.callId,reason:'declined'});stopCall(false)}
 function stopCall(notifyPeer=true){stopRing();if(notifyPeer&&call)signalRef.current?.emit('call:end',{chatId:call.chatId,callId:call.callId});pcRef.current?.close();pcRef.current=null;localStreamRef.current?.getTracks().forEach(t=>t.stop());localStreamRef.current=null;pendingOfferRef.current=null;pendingIceRef.current=[];setCall(null);setMuted(false);setCameraOff(false)}
 function toggleMute(){const t=localStreamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled)}}
 function toggleCamera(){const t=localStreamRef.current?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;setCameraOff(!t.enabled)}}
 function logout(){stopCall(false);localStorage.removeItem(USER_KEY);location.replace(location.pathname)}
 if(!me)return null;
 const activeChat=chats.find(c=>c.id===active),list=active?(messages[active]||[]):[],visibleChats=chats.filter(c=>folder==='favorites'?c.favorite:folder==='archived'?c.archived:!c.archived),counts={all:chats.filter(c=>!c.archived).length,favorites:chats.filter(c=>c.favorite&&!c.archived).length,archived:chats.filter(c=>c.archived).length},unreadTotal=Object.values(unread).reduce((a,b)=>a+Number(b||0),0),filterStyle={natural:'none',bright:'brightness(1.12) contrast(1.06) saturate(1.12)',warm:'sepia(.18) saturate(1.22) hue-rotate(-8deg)',mono:'grayscale(1) contrast(1.08)',cool:'saturate(1.05) hue-rotate(12deg) brightness(1.04)'}[filter]||'none';
 return <div className="app-shell">
  <aside className={'sidebar '+(active?'has-active':'')}><div className="brand"><MessageCircle size={25}/><strong>Pro Chat</strong><div className="brand-actions"><button title="Notifications" onClick={requestNotifications}><Bell size={19}/></button><button title="Settings" onClick={()=>setProfileView('settings')}><Settings size={19}/></button></div></div>
   <div className="profile-wrap"><button className="me-row" onClick={()=>setProfileOpen(v=>!v)}><div className="avatar">{(me.username||me.name||'P')[0].toUpperCase()}</div><div className="me-info"><b>@{me.username||me.name}</b><small>{unreadTotal?`${unreadTotal} unread message${unreadTotal===1?'':'s'}`:me.email||me.phoneNumber||''}</small></div><ChevronDown size={18}/></button>{profileOpen&&<div className="profile-menu"><button onClick={()=>{setProfileView('profile');setProfileOpen(false)}}><User size={18}/><span>My profile</span></button><button onClick={()=>{setProfileView('settings');setProfileOpen(false)}}><Settings size={18}/><span>Settings</span></button><button onClick={()=>{setProfileView('privacy');setProfileOpen(false)}}><Shield size={18}/><span>Privacy</span></button><button className="danger" onClick={logout}><LogOut size={18}/><span>Log out</span></button></div>}</div>
   <div className="search-box"><Search size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);if(!e.target.value.trim()){setResults([]);setSearchError('')}}} onKeyDown={e=>e.key==='Enter'&&find()} placeholder="Search username, email or phone"/><button onClick={()=>find()} disabled={searching}>{searching?'…':'Search'}</button></div>
   {(results.length||searchError)&&<div className="search-results">{results.map(u=><button className="user-result" key={u.id} onClick={()=>openUser(u)}><div className="avatar">{(u.username||u.name||'P')[0].toUpperCase()}</div><div><b>@{u.username||u.name}</b><span>{u.name}{u.email?' • '+u.email:''}</span></div><MessageCircle size={18}/></button>)}{searchError&&<div className="search-error">{searchError}</div>}</div>}
   <nav className="chat-folders"><button className={folder==='all'?'selected':''} onClick={()=>setFolder('all')}><MessageCircle size={16}/><span>All chats</span><em>{counts.all}</em></button><button className={folder==='favorites'?'selected':''} onClick={()=>setFolder('favorites')}><Star size={16}/><span>Favorites</span><em>{counts.favorites}</em></button><button className={folder==='archived'?'selected':''} onClick={()=>setFolder('archived')}><Archive size={16}/><span>Archived</span><em>{counts.archived}</em></button></nav>
   <div className="chat-list">{visibleChats.length?visibleChats.map(c=><div key={c.id} className={'chat-row '+(active===c.id?'active':'')} onClick={()=>openChat(c)}><div className="avatar">{(c.username||c.name||'P')[0].toUpperCase()}</div><div className="chat-meta"><b>@{c.username||c.name}{unread[c.id]?<i>{unread[c.id]}</i>:null}</b><span>{c.lastMessage||'Start a conversation'}</span></div><div className="chat-row-actions"><button title={c.favorite?'Remove favorite':'Add to favorites'} onClick={e=>{e.stopPropagation();toggleFavorite(c.id)}}><Star size={17} fill={c.favorite?'currentColor':'none'}/></button><button title={c.archived?'Unarchive':'Archive'} onClick={e=>{e.stopPropagation();toggleArchive(c.id)}}><Archive size={17}/></button></div></div>):<div className="folder-empty"><Archive size={26}/><span>{folder==='favorites'?'No favorite chats yet':folder==='archived'?'No archived chats':'No chats yet'}</span></div>}</div>
  </aside>
  <main className="chat-panel">{activeChat?<><header className="chat-header"><button className="mobile-back" onClick={()=>setActive(null)}><ChevronLeft size={22}/></button><div className="avatar">{(activeChat.username||activeChat.name||'P')[0].toUpperCase()}</div><div className="chat-title"><b>@{activeChat.username||activeChat.name}</b><small>{typing?'typing…':activeChat.name+(activeChat.email?' • '+activeChat.email:'')}</small></div><div className="chat-actions"><button title="Favorite" onClick={()=>toggleFavorite(activeChat.id)}><Star size={19} fill={activeChat.favorite?'currentColor':'none'}/></button><button title="Voice call" onClick={()=>startCall(false)}><Phone size={19}/></button><button title="Video call" onClick={()=>startCall(true)}><Video size={20}/></button><button title="More" onClick={()=>setChatMenu(v=>!v)}><MoreVertical size={20}/></button></div>{chatMenu&&<div className="chat-menu"><button onClick={()=>toggleFavorite(activeChat.id)}><Star size={17}/>{activeChat.favorite?'Remove from favorites':'Add to favorites'}</button><button onClick={()=>toggleArchive(activeChat.id)}><Archive size={17}/>{activeChat.archived?'Unarchive chat':'Archive chat'}</button></div>}</header>
   {toast&&<div className="call-banner"><span>{toast}</span><button onClick={()=>setToast('')}>×</button></div>}
   <section className="messages">{list.length?list.map(m=><div key={m.id} className={'bubble-row '+(m.senderId===me.id?'mine':'theirs')}><div className={'bubble '+(m.senderId===me.id?'mine':'theirs')}>{m.attachment?.url&&<a href={m.attachment.url} target="_blank" rel="noreferrer">📎 {m.attachment.name}</a>}<span>{m.text}</span><small>{new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} {m.senderId===me.id&&(m.status==='sent'?<Check size={13}/>:<CheckCheck size={13}/>)}</small></div></div>):<div className="conversation-empty"><MessageCircle size={34}/><span>No messages yet</span><small>Send a message to start the conversation.</small></div>}</section>
   <footer className="composer"><input ref={fileRef} type="file" hidden onChange={chooseFile}/><div className="composer-tools"><button title="Attach file" onClick={()=>fileRef.current?.click()}><Paperclip size={19}/></button><button title="Emoji" onClick={()=>setEmojiOpen(v=>!v)}><Smile size={20}/></button></div><input value={text} onChange={e=>{setText(e.target.value);emitTyping(Boolean(e.target.value.trim()))}} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&(e.preventDefault(),send())} placeholder="Type a message"/><button onClick={send} disabled={!text.trim()&&!attachment}><Send size={20}/></button>{emojiOpen&&<div className="emoji-picker">{EMOJIS.map((e,i)=><button key={i} onClick={()=>insertEmoji(e)}>{e}</button>)}</div>}{attachment&&<div className="attachment-preview">📎 {attachment.name} <button onClick={()=>setAttachment(null)}><X size={14}/></button></div>}</footer></>:<div className="empty-state"><MessageCircle size={56}/><h2>Pro Chat</h2><p>Select a chat or search a username, email or phone number to start the conversation.</p></div>}
  </main>
  {profileView&&<div className="modal-backdrop" onClick={()=>setProfileView(null)}><section className="profile-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setProfileView(null)}><X size={19}/></button>{profileView==='profile'&&<><div className="modal-avatar avatar">{(me.username||me.name||'P')[0].toUpperCase()}</div><h2>My profile</h2><div className="profile-details"><div><span>Name</span><b>{me.name||'—'}</b></div><div><span>Username</span><b>@{me.username||'—'}</b></div><div><span>Email</span><b>{me.email||'—'}</b></div><div><span>Phone</span><b>{me.phoneNumber||'—'}</b></div><div><span>Messages sent</span><b>{stats.messagesSent.toLocaleString()}</b></div><div><span>Unread messages</span><b>{stats.unreadMessages.toLocaleString()}</b></div></div></>}{profileView==='settings'&&<><h2>Settings</h2><p className="modal-note">Notifications, calling and chat preferences.</p><div className="settings-item" onClick={requestNotifications}><Bell size={19}/><span>Enable message notifications</span></div><div className="settings-item"><Mic size={19}/><span>Clear-call audio processing enabled</span></div><div className="settings-item"><Shield size={19}/><span>Secure authenticated signaling</span></div></>}{profileView==='privacy'&&<><h2>Privacy</h2><p className="modal-note">Private conversations use authenticated sessions. Voice and video media are peer-to-peer once a call connects.</p><div className="settings-item"><Shield size={19}/><span>Private conversations</span></div><div className="settings-item"><User size={19}/><span>Profile visibility</span></div></>}</section></div>}
  {call&&<div className="call-overlay"><section className="call-card">{call.video?<><video ref={remoteVideoRef} className="remote-video" autoPlay playsInline style={{filter:filterStyle}}/><video ref={localVideoRef} className="local-video" autoPlay muted playsInline/></>:<div className="voice-stage"><div className="voice-avatar avatar">{(call.username||'P')[0].toUpperCase()}</div><h2>@{call.username}</h2><p>{call.phase==='incoming'?'Incoming voice call':call.phase==='connected'?'Connected':call.phase==='calling'?'Calling…':'Connecting…'}</p></div>}<div className="call-top"><b>{call.video?'Video call':'Voice call'}</b><span>{call.phase}</span></div>{call.video&&<div className="filter-bar">{['natural','bright','warm','mono','cool'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div>}{call.phase==='incoming'?<div className="incoming"><strong>@{call.username} is calling</strong><div><button className="reject" onClick={rejectCall}><PhoneOff size={21}/></button><button className="accept" onClick={acceptCall}>{call.video?<Video size={21}/>:<Phone size={21}/>}</button></div></div>:<div className="call-controls"><button onClick={toggleMute}>{muted?<MicOff size={20}/>:<Mic size={20}/>}</button>{call.video&&<button onClick={toggleCamera}>{cameraOff?<CameraOff size={20}/>:<Camera size={20}/>}</button>}{call.video&&<button title="Switch camera" onClick={()=>{const t=localStreamRef.current?.getVideoTracks()[0];const facing=t?.getSettings()?.facingMode==='user'?'environment':'user';t?.applyConstraints({facingMode:{ideal:facing}}).catch(()=>{})}}><SwitchCamera size={20}/></button>}<button className="hang" onClick={()=>stopCall(true)}><PhoneOff size={21}/></button></div>}</section></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
