import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {io} from 'socket.io-client';
import {MessageCircle,Search,Plus,Send,Wifi,WifiOff,Phone,Video,MoreVertical,Check,CheckCheck,Users,LogOut} from 'lucide-react';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:3000';
const USER_KEY='pro-chat-user-v2',CHATS_KEY='pro-chat-chats-v2',MSG_KEY='pro-chat-messages-v2';
const cid=(a,b)=>[a,b].sort().join(':');
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
function App(){
 const [me,setMe]=useState(()=>read(USER_KEY,null)),[name,setName]=useState(''),[chats,setChats]=useState(()=>read(CHATS_KEY,[])),[messages,setMessages]=useState(()=>read(MSG_KEY,{}));
 const [active,setActive]=useState(null),[text,setText]=useState(''),[search,setSearch]=useState(''),[results,setResults]=useState([]),[online,setOnline]=useState(false),[typing,setTyping]=useState(false);
 const socket=useMemo(()=>io(API,{autoConnect:false,reconnection:true,reconnectionAttempts:Infinity}),[]);
 useEffect(()=>{if(!me)return;const connect=()=>{setOnline(true);socket.emit('presence:join',me.id);chats.forEach(c=>socket.emit('chat:join',c.id))},disc=()=>setOnline(false),incoming=m=>setMessages(x=>{const n={...x,[m.chatId]:[...(x[m.chatId]||[]).filter(v=>v.id!==m.id),m]};localStorage.setItem(MSG_KEY,JSON.stringify(n));return n}),delivered=({messageId})=>setMessages(x=>{const n={...x};for(const k in n)n[k]=n[k].map(m=>m.id===messageId?{...m,delivered:true}:m);localStorage.setItem(MSG_KEY,JSON.stringify(n));return n}),readReceipt=({messageId})=>setMessages(x=>{const n={...x};for(const k in n)n[k]=n[k].map(m=>m.id===messageId?{...m,delivered:true,read:true}:m);localStorage.setItem(MSG_KEY,JSON.stringify(n));return n}),type=e=>{if(e.userId!==me.id){setTyping(!!e.typing);setTimeout(()=>setTyping(false),1800)}};socket.on('connect',connect);socket.on('disconnect',disc);socket.on('message:new',incoming);socket.on('message:delivered',delivered);socket.on('message:read',readReceipt);socket.on('typing',type);socket.connect();return()=>socket.disconnect()},[me]);
 useEffect(()=>localStorage.setItem(CHATS_KEY,JSON.stringify(chats)),[chats]);
 async function register(){const n=name.trim();if(n.length<2)return;const old=read(USER_KEY,null);const r=await fetch(`${API}/api/users`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:old?.id,name:n})});if(!r.ok)return;const u=await r.json();localStorage.setItem(USER_KEY,JSON.stringify(u));setMe(u)}
 async function find(q=search){q=q.trim();if(!q){setResults([]);return}try{const r=await fetch(`${API}/api/users?q=${encodeURIComponent(q)}`);setResults((await r.json()).filter(u=>u.id!==me.id))}catch{setResults([])}}
 async function openUser(u){const id=cid(me.id,u.id);setChats(x=>x.some(c=>c.id===id)?x:x.concat({id,userId:u.id,name:u.name,online:!!u.online,text:'',time:''}));setActive(id);setResults([]);setSearch('');socket.emit('chat:join',id);try{const r=await fetch(`${API}/api/messages/${encodeURIComponent(id)}`);const history=await r.json();setMessages(x=>({...x,[id]:history}))}catch{}}
 function send(){const value=text.trim();if(!value||!active)return;const createdAt=new Date().toISOString(),m={id:crypto.randomUUID(),chatId:active,senderId:me.id,text:value,createdAt,delivered:false,read:false};setMessages(x=>{const n={...x,[active]:[...(x[active]||[]),m]};localStorage.setItem(MSG_KEY,JSON.stringify(n));return n});setChats(x=>x.map(c=>c.id===active?{...c,text:value,time:new Date(createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}:c));socket.emit('message:send',m);setText('')}
 if(!me)return <div className="auth"><div className="auth-card"><div className="logo big">P</div><h1>Welcome to Pro Chat</h1><p>Private, realtime and offline-first.</p><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&register()} placeholder="Your display name"/><button className="primary" onClick={register}>Continue</button><small>Your account ID is stored only on this device.</small></div></div>;
 const current=chats.find(c=>c.id===active),rows=active?messages[active]||[]:[];
 return <div className="app"><aside><div className="brand"><div className="logo">P</div><div><b>Pro Chat</b><small>{me.name}</small></div><button className="icon" onClick={()=>{localStorage.removeItem(USER_KEY);setMe(null)}}><LogOut size={17}/></button></div><div className="search"><Search size={17}/><input placeholder="Find people" value={search} onChange={e=>{setSearch(e.target.value);find(e.target.value)}}/></div>{results.length>0&&<div className="results">{results.map(u=><button key={u.id} onClick={()=>openUser(u)}><div className="avatar">{u.name[0]}</div><div><b>{u.name}</b><span>{u.online?'online':'offline'}</span></div></button>)}</div>}<div className="section">CHATS <button className="icon" onClick={()=>document.querySelector('.search input')?.focus()}><Plus size={16}/></button></div><div className="chat-list">{chats.map(c=><button className={'chat '+(c.id===active?'active':'')} onClick={()=>{setActive(c.id);socket.emit('chat:join',c.id)}} key={c.id}><div className="avatar">{c.name[0]}</div><div className="meta"><b>{c.name}</b><span>{c.text||'Start chatting'}</span></div><time>{c.time}</time></button>)}</div><div className="connection">{online?<><Wifi size={15}/> Realtime connected</>:<><WifiOff size={15}/> Offline — local queue</>}</div></aside><main><header>{current?<><div className="peer"><div className="avatar">{current.name[0]}</div><div><b>{current.name}</b><span>{typing?'typing…':current.online?'online':'offline'}</span></div></div><div className="actions"><button title="Voice call"><Phone/></button><button title="Video call"><Video/></button><button><MoreVertical/></button></div></>:<div className="peer"><div className="avatar"><MessageCircle/></div><div><b>Pro Chat</b><span>Choose a conversation</span></div></div>}</header><section className="messages">{!current&&<div className="empty"><div className="empty-icon"><Users/></div><h2>Find people to chat</h2><p>Search for another Pro Chat user above.</p></div>}{current&&rows.length===0&&<div className="empty"><div className="empty-icon"><MessageCircle/></div><h2>Start a conversation</h2><p>Say hello to {current.name}.</p></div>}{rows.map(m=><div className={'bubble-row '+(m.senderId===me.id?'mine':'')} key={m.id}><div className="bubble">{m.text}<small>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} {m.senderId===me.id&&(m.read?<CheckCheck className="read" size={14}/>:m.delivered?<CheckCheck size={14}/>:<Check size={14}/>)}</small></div></div>)}</section>{current&&<footer><input value={text} onChange={e=>{setText(e.target.value);socket.emit('typing',{chatId:active,userId:me.id,typing:true})}} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write a message…"/><button className="send" onClick={send}><Send size={19}/></button></footer>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);